name: 自动打包点名器

on:
  push:
    tags:
      - 'v*' # 当你发布以 v 开头的标签（如 v1.5）时触发

jobs:
  build:
    runs-on: windows-latest
    # 强制开启 Node.js 24 模式，彻底消除版本弃用警告
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 设置 Python 环境
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: 安装依赖
        # 这里只安装打包必须的两个库，因为代码里使用了 urllib，所以不需要安装 requests
        run: |
          pip install pygame pyinstaller

      - name: 执行打包脚本
        run: |
          python -m PyInstaller --noconsole --onefile --name "SmartPicker" dianming.py

      - name: 上传成品
        uses: softprops/action-gh-release@v2
        with:
          files: dist/SmartPicker.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
